# This is a basic workflow to help you get started with Actions

name: Dotnet Format Check

# Controls when the action will run. 
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
      - run: dotnet tool install dotnet-format

      - run: dotnet-format -f -g --check -w "Assets" --report "$GITHUB_WORKSPACE/" 

      - name: Archive format results
        uses: actions/upload-artifact@v2
        with:
          name: Dotnet-format-results
          path: $GITHUB_WORKSPACE/format-report.json
